# Generated by Django 4.1.2 on 2022-10-05 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso')),
                ('codigo_ingreso', models.CharField(max_length=10, unique=True, verbose_name='Código de Ingreso')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Costo Total')),
            ],
            options={
                'verbose_name': 'Ingreso de Producto',
                'verbose_name_plural': 'Ingresos de Productos',
            },
        ),
        migrations.CreateModel(
            name='IngresoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Costo del Producto $us')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='ingreso.ingreso')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
